name: Build and upload release artifacts
on:
  push:
    tags:
      - "*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHON_VERSION: 3.9
  TAG: ${GITHUB_REF##*/}
  SERVER_DIRECTORY: cloudpilot-server-${{ env.TAG }}
  RELEASE_NOTES: |
    **MacOS:** Please run `xattr -rd com.apply.quarantine ${{ env.SERVER_DIRECTORY }}` in order to
    remove the server components from quarantine before you run the server for the first time.
  RELEASE_TITLE: Cloudpilot ${{ env.TAG }}
  ARCHIVE_MACOS: cloudpilot-server-${{ env.TAG }}-macos-x64.zip
jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        run: gh release create ${{ env.TAG }} -d -t "${{ env.TITLE }}" -n "${{ env.RELEASE_NOTES }}"
  build-server-macos:
    runs-on: macos-10.15
    needs: create-release
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and upload
        run: |
          pip install pipenv
          cd server
          pipenv install
          pipenv run build
          cd dist
          codesign -fs - cloudpilot-server/cloudpilot-server
          mv cloudpilot-server ${{ env.SERVER_DIRECTORY }}
          zip -r ${{ env.ARCHIVE_MACOS }} ${{ env.SERVER_DIRECTORY }}
          gh release upload ${{ env.TAG }} ${{ env.ARCHIVE_MACOS }}
