name: Build and upload release artifacts
on:
  push:
    tags:
      - "*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHON_VERSION: 3.9
jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        run: gh release create ${GITHUB_REF##*/} -d -t "Cloudpilot ${GITHUB_REF##*/}"
  build-server-macos:
    runs-on: macos-10.15
    needs: create-release
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and upload
        run: |
          pip install pipenv
          cd server
          pipenv install
          pipenv run build
          cd dist
          codesign -fs - cloudpilot-server/cloudpilot-server
          zip -r cloudpilot-server-macos-x64.zip cloudpilot-server
          gh release upload ${GITHUB_REF##*/} cloudpilot-server-macos-x64.zip
