name: Build and release Cloudpilot server binaries / temporary 1.8.2
on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHON_VERSION: 3.9
  TAG: 1.8.2
  SERVER_DIRECTORY: cloudpilot-server-1.8.2
  ARCHIVE_MACOS: cloudpilot-server-1.8.2-macos-x64.zip
  ARCHIVE_WINDOWS: cloudpilot-server-1.8.2-win-x64.zip
  ARCHIVE_LINUX: cloudpilot-server-1.8.2-linux-x64.tar.gz
jobs:
  build-server-linux:
    runs-on: ubuntu-22.04
    needs: wait-for-release
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and upload
        shell: bash
        run: |
          pip install pipenv
          cd server
          echo "VERSION = \"${{ env.TAG }}\"" > version.py
          pipenv install --python ${{ env.PYTHON_VERSION }}
          pipenv run build
          cd dist
          mv cloudpilot-server ${{ env.SERVER_DIRECTORY }}
          tar -czf ${{ env.ARCHIVE_LINUX }} ${{ env.SERVER_DIRECTORY }}
          gh release upload ${{ env.TAG }} ${{ env.ARCHIVE_LINUX }}
  build-server-windows:
    runs-on: windows-2022
    needs: wait-for-release
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and upload
        shell: bash
        run: |
          pip install pipenv
          cd server
          echo "VERSION = \"${{ env.TAG }}\"" > version.py
          pipenv install --python ${{ env.PYTHON_VERSION }}
          pipenv run build
          cd dist
          mv cloudpilot-server ${{ env.SERVER_DIRECTORY }}
          7z a -r ${{ env.ARCHIVE_WINDOWS }} ${{ env.SERVER_DIRECTORY }}
          gh release upload ${{ env.TAG }} ${{ env.ARCHIVE_WINDOWS }}
  build-server-macos:
    runs-on: macos-12
    needs: wait-for-release
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and upload
        shell: bash
        run: |
          pip install pipenv
          cd server
          echo "VERSION = \"${{ env.TAG }}\"" > version.py
          pipenv install --python ${{ env.PYTHON_VERSION }}
          pipenv run build
          cd dist
          codesign -fs - cloudpilot-server/cloudpilot-server
          mv cloudpilot-server ${{ env.SERVER_DIRECTORY }}
          zip -r ${{ env.ARCHIVE_MACOS }} ${{ env.SERVER_DIRECTORY }}
          gh release upload ${{ env.TAG }} ${{ env.ARCHIVE_MACOS }}
