name: Preview release
on: workflow_dispatch
env:
  EM_VERSION: 3.1.7
  NODE_VERSION: 16
  EM_CACHE_FOLDER: emsdk
  PAGES_REPO_URL: git@github.com:cloudpilot-emu/cloudpilot-emu.github.io.git
jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - name: Setup emscripten
        uses: DirtyHairy/setup-emsdk@master
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Build wasm
        run: make -Csrc -j2 emscripten
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install node deps
        working-directory: web
        run: yarn install
      - name: Build PWA
        working-directory: web
        run: yarn build --configuration production,preview,ci --base-href /app-preview/
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
            ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Checkout pages source
        run: git clone ${{env.PAGES_REPO_URL}}
      - name: Copy and deploy
        working-directory: cloudpilot-emu.github.io
        run: |
          test -x app-preview && rm -fr app-preview
          cp -r ../web/build-pwa ./app-preview
          git add .
          git config --global user.email "golem@nowhere.org"
          git config --global user.name "The Golem"
          git commit -m "Bump."
          git push
